#!/bin/env bash
################################################################################
##
## File Name   : patchAppEnv
## Description : Patch a web/app/sched app/env using ansible to a new patch level
## Author      : Nate Werner
## Created     : 1/22/2018
##
################################################################################
##
## Syntax      : patchAppEnv -a <App Code> -e <Env Code> -y <Dom Type> -t <full_tools_verison> -w <Weblogic_Version> -v -s -b -h
## Parameters  : -a <App Code>  : (required) 2 char app code: cs, fs, hr, ih
##               -e <Env Code>  : (required) 3 char env code: dev,tst,qat,prd,per,fix,upg,trn,cls,dmo,dmn,umn,tec
##               -y <Dom Type>  : (optional) app, web, prc, or all for all types, default = all
##               -t <tools_verison> : (Required) Full tools version of PeopleTools to patch domain (ie: 8.55.13p1).
##               -w <Weblogic_Version> : (Optional) New version for Weblogic (applies to type of web or all).
##               -v             : Enable ansible debug/verbose mode
##               -s             : Use Serial mode. Changes are applied one domain at a time (rolling updates).
##                                Default = parallel (all domains at once)
##               -b             : Boot domains after patching. Use -s and -b for rolling patch without interuption to users.
##               -h             : Display this help.
## Example     : patchAppEnv.sh -a cs -e dev -y web -t 8.55.29 -w 12.1.3.0.5
##
################################################################################

### Help Instructions
function usageInfo()
{
   echo "Usage:"
   echo "  patchAppEnv upgrade all domains in an application/environment from any location,"
   echo "     using an ansible playbook, to a new patch level/version of PeopleTools and/or Weblogic."
   echo " Parameters"
   echo "     -a <App Code>  : (Required) 2 char app code: cs, fs, hr, ih"
   echo "     -e <Env Code>  : (Required) 3 char env code: dev,tst,qat,prd,per,fix,upg,trn,cls,dmo,dmn,umn,tec"
   echo "     -y <Dom Type>  : (Optional) app, web, prc, appweb, or all for all types, default = all"
   echo "     -t <tools_verison> : (Required) Full tools version of PeopleTools to apply patch for domains."
   echo "     -w <Weblogic_Version> : (Optional) new version for weblogic (applies to type of web or all)."
   echo "     -v             : Enable ansible debug/verbose mode."
   echo "     -s             : Use Single/Serial mode. Changes are applied one domain at a time (rolling updates)."
   echo "                        Default = parallel by hosts"
   echo "     -b             : Boot domains after patching.  Use -s and -b for rolling patch without interruption to users."
   echo "     -h             : Display this help"
   echo
   TOOLS_VERSION_LIST=`find /psoft/tools/8.* -maxdepth 0 -printf ','%f -type d`
   echo "Valid Tools options are: $TOOLS_VERSION_LIST"
   WEBLOGIC_VERSION_LIST=`find /psoft/weblogic/1* -maxdepth 0 -printf ','%f -type d`
   echo "Valid Weblogic options are: $WEBLOGIC_VERSION_LIST"
   echo
   echo "Sample: patchAppEnv.sh -a cs -e dev -y web -t 8.55.29 -w 12.1.3.0.5 -b"
   echo
   exit 1
}

# load bootstrap dynamic path
currentPath="$( cd "$(dirname "$0")" && pwd )"
source ${currentPath%${currentPath#*scripts*/}}library/bootstrap.sh

source $LIB_HOME/inventory.sh
source $LIB_HOME/utilities.sh
source $LIB_HOME/security.sh
source $LIB_HOME/ansible.sh

##### Variable and defaults
# Set in bootstrap:
#   ANSIBLE_HOME
#   DOMAIN_LIST
#   MAINT_HOME
#   SCRIPT_HOME

playbookFile="patch_appenv.yml"
debugFlag=""
app=""
env=""
domainType=""
newToolsVersion=""
newWeblogicVersion=""
bootDomain=""
declare -a domainList
bootVar=""
serialFlag=""
extraVars=""

##### Prompt processing and validation
while getopts "hvbsa:e:y:t:w:" optname
  do
    case "$optname" in
      "a")
        app=$OPTARG
        ;;
      "e")
        env=$OPTARG
        ;;
      "y")
        domainType=$OPTARG
        ;;
      "s")
        serialFlag="1"
        ;;
      "t")
        newToolsVersion=$OPTARG
        ;;
      "w")
        newWeblogicVersion=$OPTARG
        ;;
      "b")
        bootDomain="True"
        ;;
      "v")
        debugFlag="-vvv"
        ;;
      "h")
        usageInfo
        ;;
      "?")
        echo "Unknown option $OPTARG"
        usageInfo
        ;;
      ":")
        echo "No argument value for option $OPTARG"
        usageInfo
        ;;
      *)
      # Should not occur
        echo "Unknown error while processing options"
        ;;
    esac
  done

### Main

newShortToolsVersion="${newToolsVersion:0:4}"
# Calculate run duration
bash_start=$(date +%s)
currentDate="$(date +%y%m%d_%H%M )"
# standard logging
patchLogFile="${PS_SCRIPT_BASE}logs/maint/patchAppEnv_${app}${env}_$currentDate.log"
util::setLogFile "$patchLogFile"
stringList="$@"
util::log "DEBUG" "****Running $@"

# verifiy required fields
if [[ -z "$app" || -z "$env" ]]; then
  util::log "ERROR" "App Code and Env Code is required."
  usageInfo
fi

if [[ -z "$newToolsVersion" ]]; then
  util::log "ERROR" "New PeopleTools version is required."
  usageInfo
fi

if [ ! -e /psoft/tools/$newToolsVersion ]; then
  util::log "ERROR" "Invalid Tools version specified"
  usageInfo
fi
if [ "$domainType" == "all" ]; then
   domainType=""
fi

# get array of domains in app/env
inventory::getDomainsByEnv "$app" "$env" "$domainType" "" "$newShortToolsVersion" domainList
if [[ $? -ne 0 ]]; then
  util::log "ERROR" "Invalid app/env selected (domain::getDomainsByEnv)"
  exit 1
fi
stringList="${domainList[@]}"
util::log "DEBUG" "Domain list to be patched: $stringList"
if [[ ( "${domainType}" == *"web"* || "${domainType}" == "") && ! -e /psoft/tools/$newToolsVersion ]]; then
  util::log "ERROR" "Invalid Weblogic version specified"
  usageInfo
fi

#### Update and check domain list
echo
util::log "INFO" "Re-syncing domain list..."
if [ -n "$domaintType" ]; then
  $MAINT_HOME/syncDomainList -a $app -e $env -y $domainType
else
  $MAINT_HOME/syncDomainList -a $app -e $env
fi
util::log "INFO" "Sync Completed"
echo

util::log "INFO" "Setting up inventory for new versions"
# Now set the domain.list with the new versions to drive the patch in ansible
for eachDomain in "${domainList[@]}"; do
  inventory::upgradeDomain "$eachDomain" "" "$newToolsVersion" "$newWeblogicVersion"
  if [ $? -eq 1 ]; then
    util::log "ERROR" "Domain $eachDomain does not exist, use createDomain to create domain or re-run patchDomain with appropriate versions"
    exit 1
  fi
done

###### Ansible processing
# setup vault access (allows vault password to be sent from Rundeck)
util::log "INFO" "Setting up vault access..."
export ANSIBLE_LOG_PATH=/dev/null
sec::getandStoreVaultAccess
if [[ $? -ne 0 ]]; then
  util::log "ERROR" "Unable to setup vault access"
  exit 1
fi
# Setup log file for playbook, using same as this script
export ANSIBLE_LOG_PATH=$patchLogFile

# First, dynamically configure the playbook based on the domain being created
ansible::dynConfigPlaybook "${domainType}" "${app}${env}" "$playbookFile"

if [ -n "$bootDomain" ]; then
  bootVar="boot_domain=$bootDomain"
else
  bootVar=""
fi
# Check parallel or serial
if [ "$serialFlag" == "1" ]; then
   echo "  serial: 1" >> $ANSIBLE_HOME/$playbookFile
fi

# Run the ansible playbook
extraVars="filter_app=$app filter_env=$env filter_tools_ver=$newShortToolsVersion $bootVar"
# Run playbook
ansible::runPlaybook "$extraVars" "$debugFlag" "$playbookFile"

### Addtional summary output
bash_end=$(date +%s)
runtime=$(python2.7 -c "print '%u:%02u' % ((${bash_end} - ${bash_start})/60, (${bash_end} - ${bash_start})%60)")
domainsUpgraded=$(echo "${domainList[@]}" | sed 's/\n/\n   /g')
util::log "INFO"  "Domains upgraded: "
util::log "INFO"  "   $domainsUpgraded"
util::log "INFO"  "Run Time: $runtime"
util::log "INFO"  "Failed Tasks:"
failList=$( grep -B 1 "fatal" $patchLogFile )
if [ -z "$failList" ]; then
   util::log "INFO" "   No Failed Tasks"
else
   util::log "ERROR" "   $failList"
   exit 1
fi

# Completed domain deployment
