#!/bin/env bash
#
################################################################################
##
## File Name   : changeUserPassword.sh
## Description : Change the PS User Id's password and updates Vault
## Author      : Nate Werner
## Created     : 11/10/2019
################################################################################
## Syntax      : changeUserPassword.sh -a <app> -e <env> -u <UserId>
##
## Parameters  : -a <app>  : Optional, target app for password change
##             : -e <env>  : Target env for password change
##             : -u <userid> : PeopleSoft user id to change password for
##             :
## Example     : changeUserPassword.sh -a cs -d dev -u UMIBADMIN
##
################################################################################

# load bootstrap dynamic path
currentPath="$( cd "$(dirname "$0")" && pwd )"
source ${currentPath%${currentPath#*scripts*/}}library/bootstrap.sh

# load needed libraries
source $LIB_HOME/inventory.sh
source $LIB_HOME/utilities.sh
source $LIB_HOME/security.sh

app=""
env=""
userId=""
toolsVersion=""
admUserId="PS"

## common functions
function usageInfo()
{
   echo "Usage:"
   echo "  changeUserPassword.sh -a <app> -e <env> -u <userId>"
   echo "     Change a PeopleSoft UserId's password and update vault"
   echo "     To script, pass the userid password in env variable PS_USER_PWD"
   echo "     -a <app>  : (Required) App"
   echo "     -e <env>  : (Required) Env"
   echo "     -u <userId>: (Required) UserId to change password"
   echo "     -h               : Display this help"
   echo
   echo "Sample: changeUserPassword.sh -a cs -e dev -u UMIBADMIN"
   echo
   exit

}

######## Main program

# get user's paramters
while getopts ":ha:e:u:" optname; do
    case "$optname" in
      "a")
        app=$OPTARG
        ;;
      "e")
        env=$OPTARG
        ;;
      "u")
        userId=$OPTARG
        ;;
      "t")
        toolsVersion=$OPTARG
        ;;
      "h")
        usageInfo
        ;;
      "?")
        echo "Unknown option $OPTARG"
        usageInfo
        ;;
      ":")
        echo "No argument value for option $OPTARG"
        usageInfo
        ;;
      *)
      # Should not occur
        echo "Unknown error while processing options"
        ;;
    esac
done

# verifiy required fields
if [[ -z "$env" ]]; then
  echo "Environment is required."
  usageInfo
fi

# setup log file for process
currentDate="$(date +%y%m%d_%H%M )"
passLogFile="$PS_SCRIPT_BASE/logs/maint/changeUserPassword_${app}_${env}_${userId}_$currentDate.log"
util::setLogFile "$passLogFile"

# Setup Vault access
export ANSIBLE_LOG_PATH=/dev/null
sec::getandStoreVaultAccess
if [[ $? -ne 0 ]]; then
  util::log "ERROR" "Unable to setup vault access"
  exit 1
fi

# Get the Umsuper password
sec::getGenSecurity "ps" admUserPass

# check if passed in with env variable
if [ -z "$PS_USER_PWD" ]; then
  echo -n "Enter new $app$env $userId Password:"
  read -s newUserPass
  echo
  echo -n "Re-Enter new $app$env $userId Password:"
  read -s newUserPass2
  echo

  if [[ "$newUserPass" != "$newUserPass2" ]]; then
    echo "Password does not match!"
    exit 1
  fi
else
  # Use password stored in env var
  newUserPass="$PS_USER_PWD"
fi

# only the $# seem to be safe with all various login scenarios
if [[ $newUserPass =~ ['!@%^&*()+|{};:/?.'] ]]; then
  echo "An invalid character that can cause login problems was used ('!@%^&*()+|{};:/?.').  Retry without these characters."
  exit 1
fi

util::log "INFO" "Starting password change process for ${app}${env}'s $userId"

# Check for invalid characters in password

if [[ "$app" == "" ]]; then
  appList=( "cs" "fs" "hr" "ih" )
else
  appList=( "$app" )
fi

# apply password change to each app
for eachApp in ${appList[@]}; do
  # Setup DMS script
  util::log "DEBUG" "Starting changeUserPassword for $userId at ${eachApp}$env"
  # To run dms command we will determine where the scheduler is running and execute the dms there
  majorToolsVer=$( inventory::getCurrentToolsAppEnv "$eachApp" "$env" "prc")
  inventory::getDomainsByEnv "$eachApp" "$env" "prc" "$majorToolsVer" domainList
  # Grab the first scheduler, we'll run it there
  inventory::getDomainInfo "${domainList[0]}" "" "$majorToolsVer" domAttribs
  dmsHost="${domAttribs[$DOM_ATTR_HOST]}"
  util::log "DEBUG" "Using ${domAttribs[$DOM_ATTR_HOST]} from domain ${domainList[0]} to run psdmtx"

  configFile="/psoft/admin/tmp/.dmxcfg${currentDate}.txt"
  scriptFile="/psoft/admin/tmp/.accessid${currentDate}.dms"
  echo "update PSOPRDEFN set PTOPERPSWDV2 = '$newUserPass', OPERPSWDSALT = ' ', OPERPSWD = ' ', ENCRYPTED = 0 where OPRID = '$userId';" > $scriptFile

  echo "ENCRYPT_PASSWORD $userId;" >> $scriptFile

  #Write config
  cat <<EOT > $configFile
-CT ORACLE
-CD ${eachApp^^}${env^^}
-CO $admUserId
-CP "$admUserPass"
-FP $scriptFile
EOT

  # Now run script on scheduler
  util::log "DEBUG" "Running DMS: $SSH_CMD $dmsHost \"source $eachApp$env.env && PS_SERVER_CFG=\$PS_CFG_HOME/appserv/prcs/$eachApp$env/psprcs.cfg psdmtx $configFile\""
  dmsResult=$( $SSH_CMD $dmsHost "source $eachApp$env.env && PS_SERVER_CFG=\$PS_CFG_HOME/$eachApp/appserv/prcs/$eachApp$env/psprcs.cfg psdmtx $configFile" )
  dmsExitCode=$?
  # DMX will auto delete the config file, but script needs to be cleared
  rm $scriptFile
  if [ -e $configFile ]; then
     rm $configFile
  fi
  util::log "DEBUG" "DMS Exit Code: $dmsExitCode, Result: $dmsResult"
  # Check for errors
  if [[ "$dmsResult" == *"Successful completion"* ]]; then
     util::log "INFO" "DMS Change User Password Successful in $eachApp$env."
  else
     util::log "ERROR" "Failed to run DMS Change User Password, aborting, Results:  $dmsResult"
     exit 1
  fi

done
util::log "INFO" "Make sure to update ansible vault with new password"
#END
